from datetime import datetime
from configuration import Configuration as Config

gray_sis_field_dynamic_values = None

def init_gray_field_dynamic_values():

    global gray_sis_field_dynamic_values
    if gray_sis_field_dynamic_values is None:

        gray_sis_field_dynamic_values = {
          "Individual-Requesting-Software-Text": "Matthew Windham",
          "Date-YYYYMMDD-Text": datetime.now().strftime("%Y%m%d"),
          "IPT-Text": "F-35, Common Reprogramming Tool",
          "Server-Checkbox": "/On",
          "Client-Checkbox": "/On",
          "Windows-Checkbox": "/On",
          "Linux-Checkbox": "/On",
          "UNIX-Checkbox": "",
          "Other-Checkbox": "",
          "IS-Deployment-Text": "Gray",
          "Administrative-Checkbox": "",
          "Analysis-Checkbox": "",
          "Deliverable-Checkbox": f"{Config.is_deliverable_checkbox}",
          "DevelopmentTest-Checkbox": "/On",
          "Simulations-Checkbox": "",
          "Unclassified-Checkbox": "",
          "Secret-Checkbox": "",
          "SecretSAR-Checkbox": "/On",
          "Product-Title-Text": f"See attached {Config.sis_csv_file_name}",
          "Product-Version-Text": f"See attached {Config.sis_csv_file_name}",
          "Vendor-Creator-Text": f"See attached {Config.sis_csv_file_name}",
          "Vendors-Website-Text": f"See attached {Config.sis_csv_file_name}",
          "Mission-Driven-Justification-Text": "For the development and testing of the F-35 Common Reprogramming Tool.",
          "Mission-Impact-If-Not-Approved-Text": "Failure to develop software for F-35 CRT would materially impact the CRT program and could result in lost contracts.",
          "Upgrade-Downgrade-Radio-Buttons": "",
          "If-No-Versions-Approved-Why-Is-It-Required-Text": "",
          "If-Operating-System-Radio-Buttons": "/If Operating System will otherOperating Systems be_NA_On",
          "United-States-Checkbox": "",
          "Foreign-List-Country": "",
          "Foreign-List-Country-Checkbox": "",
          "If-Vendor-Country-Unknown-Checkbox": "/On",
          "COTS/GOTS-Solution-Available-Radio-Buttons": "/If foreign open source or freewareis there any alt_No_On",
          "Vulnerability-Assessment-No-Checkbox": "",
          "Vulnerability-Assessment-Yes-Checkbox": "/On",
          "High-Checkbox": "",
          "Moderate-Checkbox": "",
          "Low-Checkbox": "",
          "Is-Executable-Radio-Buttons": f"{Config.is_executable_radio_button}",
          "System-Level-Checkbox": "",
          "Root-Admin-Checkbox": "",
          "Single-User-Checkbox": "",
          "Authenticated-User-Checkbox": "",
          "Are-There-Dependencies-Radio-Buttons": f"{Config.has_dependencies_radio_button}",
          "Create-Non-standard-File-Radio-Buttons": "/Does it create a nonstandard file_No_On",
          "Can-Be-Scanned-By-Security-Software-Radio-Buttons": "/If Yes identify file type_Yes_On",
          "Has-Software-Been-Modified-Radio-Buttons": "/Has software been modified If Yesjustify the reaso_No_On",
          "Software-Modified-Vendor-Checkbox": "",
          "Software-Modified-In-House-Checkbox": "",
          "Software-Modified-Third-Party-Checkbox": "",
          "Procurement-In-House-Checkbox": "",
          "Procurement-GOTS-Checkbox": "",
          "Procurement-COTS-Checkbox": "",
          "Procurement-Freeware-Checkbox": "",
          "Procurement-Foreign-Checkbox": "",
          "Procurement-Open-Source-Checkbox": "/On",
          "Alternative-Solutions-Available-Radio-Buttons": "/Are there any alternative solutionsavailable_No_On",
          "Not-Open-Source-Checkbox": "",
          "eFOSS-Process-No-Checkbox": "",
          "eFOSS-Process-Yes-Checkbox": "/On",
          "IronFOSS-Radio-Buttons": "/If Open Source has the softwarebeen through the Ir_Yes_On",
          "JSON-And-CSV-Attached-Checkbox": "/On",
          "Unclassified-Score-Text": f"See attached {Config.sis_csv_file_name}",
          "Software-Used-For-Deliverable-Radio-Buttons": Config.is_deliverable_radio_button,
          "Collaborative-Computing-Checkbox": "",
          "Distributive-Processing-Checkbox": "",
          "Dongle-Required-Checkbox": "",
          "Office/Productivity-Checkbox": "",
          "Operational-Tactical-Checkbox": "/On",
          "Programming/Coding-Checkbox": "",
          "Security-Relevant-Checkbox": "",
          "Intended-Use-Other-Describe-Checkbox": "",
          "Office-Space-Checkbox": "",
          "Lab-Checkbox": "/On",
          "SDD-Checkbox": "",
          "DT-Flight-Test-Checkbox": "",
          "LRIP-Checkbox": "",
          "Production-Support-Checkbox": "",
          "End-Use-Other-Describe-Checkbox": "",
          "I-Am-Cleared-And-Possess-Account": "/On",
          "Requested-Software-Will-Adversely-Impact": "",
          "ISSO-Reviewer-Text": "",
          "Approved-Checkbox": "",
          "Denied-Checkbox": "",
          "Vendor-Country-Unknown-Text": "Analysis on collateral/SAP networks",
          "Vulnerability-Assessment-No-Text": "",
          "Vulnerability-Assessment-Yes-Text": f"See attached {Config.vuln_file_name}",
          "Vulnerability-Justify-Risk-Determination-Text": "",
          "Dependencies-Yes-Text": f"See attached {Config.sbom_output_file_path}",
          "Alternative-Solutions-Yes-Text": "",
          "Signature6": "",
          "Signature7": "",
          "Justify-COTS/GOTS-Not-Used-Text": "",
          "Upgrade-Downgrade-Yes-Text": "",
          "Intended-Use-Other-Describe-Text": "",
          "End-Use-Other-Describe-Text": "",
          "eFOSS-Process-No-Text": "",
          "Software-Modified-Yes-Text": ""
        }

        return gray_sis_field_dynamic_values
